[package]
name = "demo-app"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[[bin]]
name = "showcase"
path = "src/main.rs"

[dependencies]
demo = { path = "../demo" }
iced = { version = "0.14", features = ["advanced", "canvas", "svg", "image", "lazy", "tokio"] }
